spring:
  application:
      name: CloudGateWay

server:
  port: ${PORT:2226}

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2221/eureka/
  instance:
    hostname: ${spring.cloud.client.hostname}

zuul:
  routes:
    product:
      path: /products/**
      serviceId: product
      stripPrefix: false
    display:
      path: /displays/**
      serviceId: display
      stripPrefix: false