spring:
  application:
    name: CloudConfig
  cloud:
    config:
      server:
        git:
#          uri:/Users/swmoon/Dev/Source/Config/SPRING-CLOUD-SAMPLE-CONFIG
          uri: https://github.com/mctlmk1/msa_config.git
          username: mctlmk1
          password: mctlmk!1
#          basedir: target/config
          force-pull: true


server:
  port: ${PORT:8004}

management:
  security:
    enabled: false
