spring:
  application:
      name: CloudAdmin

server:
  port: ${PORT:2223}


# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2221/eureka/
  instance:
    hostname: ${spring.cloud.client.hostname}